# Generated by Django 2.1.7 on 2019-04-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='relatedtask',
            field=models.TextField(null=True),
        ),
    ]
