# Generated by Django 2.1.7 on 2019-04-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190416_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=50)),
                ('player', models.EmailField(max_length=254)),
                ('host', models.CharField(max_length=50)),
                ('extime', models.DateTimeField()),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
