# Generated by Django 2.1.7 on 2019-04-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='extime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
